# Generated by Django 3.1.1 on 2021-06-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_Cores',
            field=models.ManyToManyField(help_text='Aim to limit to 5 core skills.', related_name='Core_Skills', to='Resume.skill', verbose_name='Core Skills'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_Employer_Phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_Skills',
            field=models.ManyToManyField(help_text='Include only the most relevant skills.', related_name='Relevant_Skills', to='Resume.skill', verbose_name='Relevant Skills'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer_Address',
            field=models.TextField(blank=True, max_length=100, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('3', 'Pending'), ('0', '---'), ('2', 'In Progress')], default='0', help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
    ]
