# Generated by Django 3.1.1 on 2021-06-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_auto_20210613_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_Date', models.DateField(blank=True, help_text='When did you receive the award?', null=True, verbose_name='Date')),
                ('award_Name', models.CharField(help_text='What is the name of the award?', max_length=200, verbose_name='Title')),
                ('award_Organization', models.CharField(help_text='Issuer or Institution', max_length=200, verbose_name='Organization')),
                ('award_Description', models.TextField(blank=True, help_text='i.e. general description, specialization, grade, series, etc', max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['award_Date', 'award_Name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Comments',
            field=models.ManyToManyField(blank=True, help_text='Notes about the application process.', to='Resume.app_Comments', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Education',
            field=models.ManyToManyField(help_text='You can include all of your educational history, here.', to='Resume.university', verbose_name='Educational History'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer',
            field=models.CharField(help_text='Which company are you applying to?', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer_Address',
            field=models.TextField(blank=True, help_text='Usually the office you are applying to or HQ if remote role.', max_length=100, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer_Phone',
            field=models.CharField(blank=True, help_text='Primary company contact number to reach Human Resources.', max_length=100, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Experience',
            field=models.ManyToManyField(help_text='It is recommended to list only related roles to the job you are applying to.', to='Resume.job', verbose_name='Work Experience'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Independent',
            field=models.ManyToManyField(help_text='Add courses, certifications, or other items here.', to='Resume.course', verbose_name='Independent Learning'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Job_Description',
            field=models.TextField(blank=True, help_text='You can copy/paste job post details here.', max_length=5000, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Job_Number',
            field=models.CharField(blank=True, help_text='This will be on the job post if one is given.', max_length=100, verbose_name='Job ID #'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Link',
            field=models.URLField(blank=True, help_text='What is the link to the job posting?', null=True, verbose_name='Job URL'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Profile',
            field=models.OneToOneField(help_text='Required for identifying you on the resume.', on_delete=django.db.models.deletion.CASCADE, to='Resume.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Title',
            field=models.CharField(help_text='Enter a name for the resume.', max_length=100, verbose_name='Resume Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('3', 'Pending'), ('2', 'In Progress')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_Current',
            field=models.BooleanField(verbose_name='This Is My Current Employer'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_Awards',
            field=models.ManyToManyField(help_text='Add awards or other items here.', to='Resume.awards', verbose_name='Awards'),
        ),
    ]
