# Generated by Django 3.1.1 on 2021-06-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_auto_20210613_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_Icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_Link',
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Awards',
            field=models.ManyToManyField(blank=True, help_text='<strong>Add awards or other items here.</strong><br/>', to='Resume.awards', verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Comments',
            field=models.ManyToManyField(blank=True, help_text='<strong>Notes about the application process.</strong><br/>', to='Resume.app_Comments', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Cores',
            field=models.ManyToManyField(blank=True, help_text='<strong>Aim to limit to 5 core skills.</strong><br/>', related_name='Core_Skills', to='Resume.skill', verbose_name='Core Skills'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Education',
            field=models.ManyToManyField(blank=True, help_text='<strong>You can include all of your educational history, here.</strong><br/>', to='Resume.university', verbose_name='Educational History'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer',
            field=models.CharField(help_text='<strong>Which company are you applying to?<br/>This will be used on the cover letter.</strong>', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer_Address',
            field=models.TextField(blank=True, help_text='<strong>Usually the office you are applying to or HQ if remote role.</strong>', max_length=100, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Employer_Phone',
            field=models.CharField(blank=True, help_text='<strong>Primary company contact number to reach Human Resources.</strong>', max_length=100, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Experience',
            field=models.ManyToManyField(help_text='<strong>It is recommended to list only related roles to the job you are applying to.</strong><br/>', to='Resume.job', verbose_name='Work Experience'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Independent',
            field=models.ManyToManyField(blank=True, help_text='<strong>Add courses, certifications, or other items here.</strong><br/>', to='Resume.course', verbose_name='Independent Learning'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Job_Description',
            field=models.TextField(blank=True, help_text='<strong>You can copy/paste job post details here.</strong>', max_length=5000, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Job_Number',
            field=models.CharField(blank=True, help_text='<strong>This will be on the job post if one is given.</strong>', max_length=100, verbose_name='Job ID #'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Job_Title',
            field=models.CharField(help_text='<strong>This will be used on the cover letter.</strong>', max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Link',
            field=models.URLField(blank=True, help_text='<strong>What is the link to the job posting?</strong>', null=True, verbose_name='Job URL'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Links',
            field=models.ManyToManyField(blank=True, help_text='<strong>Add relevant links, here (i.e. portfolio, website, social media).</strong><br/>', to='Resume.link', verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Profile',
            field=models.OneToOneField(help_text='<strong>Required for identifying you on the resume.</strong>', on_delete=django.db.models.deletion.CASCADE, to='Resume.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Skills',
            field=models.ManyToManyField(blank=True, help_text='<strong>Include only the most relevant skills.</strong><br/>', related_name='Relevant_Skills', to='Resume.skill', verbose_name='Relevant Skills'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Status',
            field=models.BooleanField(default=False, help_text='<strong>Check if your application has been rejected.</strong>', verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Title',
            field=models.CharField(help_text='<strong>Enter a name for the resume.</strong>', max_length=100, verbose_name='Resume Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_Info',
            field=models.CharField(help_text='<strong>Add your contact detail here, (i.e. phone number, email address, home address, etc).</strong><br/>', max_length=100, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_Type',
            field=models.CharField(help_text='<strong>Phone, Email, Address, etc.</strong><br/>', max_length=100, verbose_name='Type'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_Contact',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_Contact',
            field=models.ManyToManyField(help_text='<strong>Add your contact details here.</strong><br/>', to='Resume.contact', verbose_name='Contact List'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_Name',
            field=models.CharField(help_text='<strong>What name should be on your resume?</strong><br/>', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_Objective',
            field=models.OneToOneField(help_text='<strong>This will be your profile or career objective.</strong><br/>', on_delete=django.db.models.deletion.CASCADE, to='Resume.objective', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_Title',
            field=models.CharField(blank=True, help_text='<strong>What is the job title you are aiming for?</strong><br/>', max_length=200, verbose_name='Title'),
        ),
    ]
