# Generated by Django 3.1.1 on 2021-06-14 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_auto_20210614_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_comments',
            name='app_Ref',
            field=models.ForeignKey(help_text='<strong>What app does this belong to?</strong>', null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.application', verbose_name='App References'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_Notes',
            field=models.ManyToManyField(blank=True, help_text='<strong>Notes about the application process.</strong><br/>', to='Resume.app_Comments', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_Cores',
            field=models.ManyToManyField(blank=True, help_text='<strong>Aim to limit to 5 core skills.</strong><br/>', to='Resume.core', verbose_name='Core Skills'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In Progress'), ('3', 'Pending')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
    ]
