# Generated by Django 3.1.1 on 2021-06-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_auto_20210614_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_App_Ref',
            field=models.OneToOneField(blank=True, help_text='<strong>What app do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('3', 'Pending'), ('2', 'In Progress'), ('1', 'Completed')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
    ]
