# Generated by Django 3.1.1 on 2021-06-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0010_auto_20210614_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_Profile_Ref',
            field=models.OneToOneField(blank=True, help_text='<strong>What profile do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.profile'),
        ),
        migrations.AddField(
            model_name='objective',
            name='objective_Profile_Ref',
            field=models.OneToOneField(blank=True, help_text='<strong>What profile do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('3', 'Pending'), ('2', 'In Progress')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
    ]
