# Generated by Django 3.1.1 on 2021-06-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0011_auto_20210614_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile Header', 'verbose_name_plural': 'Profile Headers'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_Contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_Objective',
        ),
    ]
