# Generated by Django 3.1.1 on 2021-06-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0012_auto_20210614_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_Profile_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What profile do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.profile'),
        ),
    ]
