# Generated by Django 3.1.1 on 2021-06-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0014_auto_20210614_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What app do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('2', 'In Progress'), ('1', 'Completed'), ('3', 'Pending')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_Profile_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What profile do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='Resume.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What app do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_Category_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What category do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='Resume.category'),
        ),
        migrations.AlterField(
            model_name='university',
            name='uni_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uni', to='Resume.application'),
        ),
    ]
