# Generated by Django 3.1.1 on 2021-06-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0015_auto_20210614_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_Phonetic',
            field=models.CharField(blank=True, help_text='<strong>How do we pronounce your name?</strong><br/>', max_length=100, verbose_name='Phonetic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_App_Ref',
            field=models.ForeignKey(blank=True, help_text='<strong>What application do you want to attach this to?</strong><br/>', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ind', to='Resume.application'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Progress',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], help_text='Complete, In Progress, Pending', max_length=200, verbose_name='Progress'),
        ),
    ]
